const modal = document.querySelector(".modal");
const overlay = document.querySelector(".overlay");
const btnCloseModal = document.querySelector(".close-modal");
const btnsOpenModal = document.querySelector(".show-modal");
const productsList = document.querySelector(".productList");
const productName = document.querySelector(".productName");
const reviewsContainer = document.querySelector(".reviews");
const container = document.querySelector(".container");
const ratingDiv = document.querySelector(".ratingDiv");
const reviewTextInput = document.querySelector(".review");
const loading=document.querySelector('.loading')
const error=document.querySelector('.error')
const form = document.querySelector(".form");
const averageRatingNumber = document.querySelector(".ratingNumber");